<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted } from 'vue';
import { usePortfolioStore } from '../stores/portfolio';
import { companies } from '../data/companies';

const store = usePortfolioStore();
const company = computed(() => companies[store.companyIndex]);
const isAr = computed(() => store.language === 'ar');
let observer: MutationObserver | undefined;
onMounted(() => { const sync = () => store.setLanguage(document.documentElement.lang === 'en' ? 'en' : 'ar'); sync(); observer = new MutationObserver(sync); observer.observe(document.documentElement, { attributes: true, attributeFilter: ['lang', 'dir'] }); });
onBeforeUnmount(() => observer?.disconnect());
function contactHref(c: any) { const subject = isAr.value ? `مناقشة منتجات — ${c.nameAr}` : `Products discussion — ${c.nameEn}`; return `mailto:partners@targetft.com?subject=${encodeURIComponent(subject)}`; }
</script>

<template>
  <section class="portfolio-app" :dir="isAr ? 'rtl' : 'ltr'">
    <div class="portfolio-company-grid" role="tablist" :aria-label="isAr ? 'الشركات والمنتجات محل الاهتمام' : 'Companies and products in focus'">
      <button v-for="(c, ci) in companies" :key="c.id" type="button" class="company-tile" :class="{ active: store.companyIndex === ci }" role="tab" :aria-selected="store.companyIndex === ci" @click="store.selectCompany(ci)">
        <span class="company-tile-top"><span class="company-tile-mark">{{ String(ci + 1).padStart(2, '0') }}</span><span class="company-tile-state">{{ isAr ? 'استعرض السجل' : 'View record' }}</span></span><span class="company-tile-content"><span class="company-kicker">{{ isAr ? 'ضمن نطاق الاهتمام' : 'Within current focus' }}</span><strong>{{ isAr ? c.nameAr : c.nameEn }}</strong><small>{{ isAr ? c.categoryAr : c.categoryEn }}</small><span class="company-count">{{ c.products.length }} {{ isAr ? 'أصناف مدرجة' : 'listed items' }}</span></span>
      </button>
    </div>
    <article class="portfolio-detail" role="tabpanel">
      <header class="company-summary"><span class="portfolio-label">{{ isAr ? 'شركات ومنتجات محل اهتمامنا' : 'Companies & Products in Focus' }}</span><h3>{{ isAr ? company.nameAr : company.nameEn }}</h3><p class="company-category">{{ isAr ? company.categoryAr : company.categoryEn }}</p><p class="company-description">{{ isAr ? company.descriptionAr : company.descriptionEn }}</p><p v-if="'noteAr' in company" class="company-note">{{ isAr ? company.noteAr : company.noteEn }}</p><div class="claim-note"><i class="bi bi-shield-check"></i><span>{{ isAr ? 'عرض تعريفي فقط؛ ولا يعني وكالة أو تمثيلًا أو حصرية.' : 'For information only; no agency, representation or exclusivity is implied.' }}</span></div></header>
      <section class="company-products" :aria-label="isAr ? 'الأصناف المسجلة' : 'Listed products'"><div class="company-products-head"><div><span class="portfolio-label">{{ isAr ? 'الأصناف المسجلة' : 'Listed products' }}</span><h3>{{ isAr ? `منتجات ${company.nameAr}` : `${company.nameEn} products` }}</h3></div><span class="product-count">{{ company.products.length }} {{ isAr ? 'صنفًا' : 'items' }}</span></div><p class="products-intro">{{ isAr ? 'الأسماء التالية مستندة إلى مصدر المحتوى المعتمد. تُضاف صور العبوات أو ملفات المنتجات بعد اعتمادها.' : 'The names below follow the approved content source. Product images or files are added after approval.' }}</p><ul class="company-product-list"><li v-for="(p, pi) in company.products" :key="p.slug"><span>{{ String(pi + 1).padStart(2, '0') }}</span>{{ isAr ? p.nameAr : p.nameEn }}</li></ul><a class="portfolio-contact" :href="contactHref(company)"><i class="bi bi-envelope"></i>{{ isAr ? 'ناقش المنتجات' : 'Discuss products' }}</a></section>
    </article>
  </section>
</template>

<style>
.portfolio-app{--green:#0c4931;--deep:#073b29;--sand:#c09552;--line:#e4ded5;--ink:#242824;color:var(--ink)}
.portfolio-company-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-bottom:24px}.company-tile{position:relative;min-height:184px;padding:20px;border:1px solid var(--line);border-radius:18px;background:#fff;color:var(--ink);text-align:inherit;box-shadow:0 12px 30px rgba(12,73,49,.06);transition:.2s}.company-tile:hover,.company-tile.active{border-color:var(--sand);background:#0c4931;color:#fff;box-shadow:0 18px 34px rgba(12,73,49,.16);transform:translateY(-2px)}.company-tile-mark{position:absolute;inset-inline-end:16px;top:15px;color:var(--green);font:800 .72rem/1 Manrope,sans-serif}.company-tile.active .company-tile-mark{color:#ead3a6}.company-tile-content{display:grid;align-content:end;min-height:142px;gap:6px}.company-kicker,.portfolio-label{color:var(--green);font-size:.72rem;font-weight:800}.company-tile.active .company-kicker{color:#ead3a6}.company-tile-content strong{font-size:1.34rem}.company-tile-content small{line-height:1.55;color:#69716b}.company-tile.active small{color:rgba(255,255,255,.83)}.company-count{margin-top:4px;font-size:.75rem;font-weight:700;color:#778078}.company-tile.active .company-count{color:#fff}
.portfolio-detail{display:grid;grid-template-columns:minmax(270px,.76fr) minmax(0,1.5fr);gap:18px}.company-summary,.company-products{padding:25px;border:1px solid var(--line);border-radius:20px;background:#fff;box-shadow:0 14px 34px rgba(12,73,49,.06)}.company-summary h3,.company-products h3{margin:.45rem 0;font-size:1.8rem}.company-category{color:var(--green);font-weight:800}.company-description{color:#606860;line-height:1.8}.company-note{padding:11px 12px;border-radius:11px;background:#faf5ed;color:#5f625d;font-size:.8rem;line-height:1.6}.claim-note{display:flex;gap:8px;margin-top:16px;padding:12px;border-radius:11px;background:#eef5f1;color:var(--green);font-size:.79rem;line-height:1.55}.company-products-head{display:flex;align-items:flex-start;justify-content:space-between;gap:14px}.product-count{padding:7px 10px;border-radius:999px;background:#eef5f1;color:var(--green);font-size:.76rem;font-weight:800;white-space:nowrap}.products-intro{margin:15px 0;color:#69716b;line-height:1.75;font-size:.9rem}.company-product-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin:0;padding:0;list-style:none}.company-product-list li{display:flex;align-items:center;gap:10px;min-height:48px;padding:10px 12px;border:1px solid var(--line);border-radius:11px;background:#fff;color:#3f4841;font-size:.88rem;font-weight:700}.company-product-list li span{color:var(--sand);font:800 .68rem/1 Manrope,sans-serif}.portfolio-contact{display:inline-flex;align-items:center;justify-content:center;gap:8px;margin-top:16px;padding:11px 15px;border-radius:10px;background:var(--green);color:#fff;text-decoration:none;font-weight:800}.portfolio-contact:hover{background:var(--deep);color:#fff}
@media(max-width:1100px){.portfolio-company-grid{grid-template-columns:repeat(2,1fr)}.portfolio-detail{grid-template-columns:1fr}.company-summary{padding:23px}}@media(max-width:700px){.portfolio-company-grid{grid-template-columns:1fr 1fr;gap:10px;margin-bottom:16px}.company-tile{min-height:160px;padding:15px;border-radius:15px}.company-tile-mark{inset-inline-end:12px;top:12px}.company-tile-content{min-height:126px;gap:5px}.company-tile-content strong{font-size:1.16rem}.company-tile-content small{font-size:.75rem;line-height:1.45}.company-count{font-size:.68rem}.portfolio-detail{gap:12px}.company-summary,.company-products{padding:18px;border-radius:16px}.company-summary h3,.company-products h3{font-size:1.5rem}.company-description{font-size:.9rem}.company-products-head{align-items:center}.products-intro{font-size:.84rem}.company-product-list{grid-template-columns:1fr}.company-product-list li{min-height:45px;font-size:.84rem}.portfolio-contact{display:flex;width:100%;min-height:48px}}

/* Lead-page treatment */
.company-tile-top{position:absolute;inset-inline:16px;inset-block-start:15px;display:flex;align-items:center;justify-content:space-between;gap:8px}.company-tile-mark{position:static!important}.company-tile-state{padding:5px 8px;border:1px solid rgba(12,73,49,.12);border-radius:999px;background:#f5f8f5;color:var(--green);font-size:.65rem;font-weight:800;opacity:0;transform:translateY(-3px);transition:.2s}.company-tile:hover .company-tile-state,.company-tile.active .company-tile-state{opacity:1;transform:none}.company-tile.active .company-tile-state{border-color:rgba(255,255,255,.18);background:rgba(255,255,255,.12);color:#fff}
.portfolio-detail{padding:8px;border:1px solid rgba(12,73,49,.08);border-radius:24px;background:linear-gradient(145deg,#edf4ef,#fbf8f2)}.company-summary{position:relative;overflow:hidden;border:0;background:linear-gradient(155deg,#0c5138,#073b29);color:#fff;box-shadow:0 18px 36px rgba(7,59,41,.15)}.company-summary::after{content:'';position:absolute;inset-inline-end:-80px;inset-block-start:-70px;width:230px;height:230px;border-radius:50%;background:radial-gradient(circle,rgba(216,184,121,.28),transparent 67%)}.company-summary>*{position:relative;z-index:1}.company-summary .portfolio-label{color:#e3c38d}.company-summary h3{color:#fff}.company-summary .company-category{color:#e6c993}.company-summary .company-description{color:rgba(255,255,255,.78)}.company-summary .company-note{background:rgba(255,255,255,.10);color:rgba(255,255,255,.84)}.company-summary .claim-note{background:rgba(255,255,255,.11);color:#fff}.company-products{border:0;box-shadow:none}.company-product-list li{transition:border-color .18s ease,transform .18s ease;background:#fff}.company-product-list li:hover{border-color:#cfa66b;transform:translateY(-1px)}.portfolio-contact{min-height:50px;border-radius:13px;box-shadow:0 10px 20px rgba(12,73,49,.16)}
@media(max-width:700px){.portfolio-app{margin-inline:-.1rem}.portfolio-company-grid{display:grid!important;grid-template-columns:1fr 1fr!important;overflow:visible!important;scroll-snap-type:none!important;padding:0!important;gap:10px!important}.company-tile{min-width:0!important;min-height:142px!important;padding:14px!important;border-radius:18px!important}.company-tile-top{inset-inline:13px!important;inset-block-start:12px!important}.company-tile-state{display:none}.company-tile-content{min-height:111px!important;gap:4px!important}.company-tile-content strong{font-size:1.1rem!important;line-height:1.2}.company-tile-content small{font-size:.72rem!important}.company-count{margin-top:3px!important;font-size:.66rem!important}.portfolio-detail{display:grid!important;grid-template-columns:1fr!important;gap:0!important;padding:0!important;border-radius:20px!important;background:transparent!important}.company-summary{border-radius:20px 20px 0 0!important;padding:21px 18px!important}.company-products{border-radius:0 0 20px 20px!important;padding:20px 18px!important;box-shadow:0 12px 28px rgba(12,73,49,.07)!important}.company-summary h3,.company-products h3{font-size:1.45rem!important}.company-product-list li{min-height:49px!important;border-radius:12px!important}.portfolio-contact{margin-top:18px!important}}

</style>
